<span style="color:black;font-size: 30px; font-family: Arial; font-weight: bold;"> EDUNET FOUNDATION-Self Paced Solution Notebook</span>

<span style="color:black;font-size: 25px; font-family: Arial; font-weight: bold;"> Lab 1: NumPy for Data Manipulation</span>

<span style="color:black;font-size: 25px; font-family: Arial; font-weight: bold;"> Problem 1: Create a 1 D NumPy array from a list </span>

In [2]:
import numpy as np

# Create a variable called my_array, and pass a list to the array() function
myArray_1D = np.array([1,2,3,4,5,6,7])

print(myArray_1D)

[1 2 3 4 5 6 7]


<span style="color:black;font-size: 25px; font-family: Arial; font-weight: bold;"> Problem 2: Create a 2 D NumPy array from a list.</span>

In [3]:
import numpy as np

# Pass 2 lists into the function
myArray_2D = np.array([[1,2,3,4],[5,6,7,8]])

print(myArray_2D)

[[1 2 3 4]
 [5 6 7 8]]


<span style="color:black;font-size: 25px; font-family: Arial; font-weight: bold;"> Problem 3: Print the shape, dimensionality and Size of the above array. </span>

In [6]:
# Second array

print("Shape of array 2:\n", myArray_2D.shape)
print("Dimensionality of array 2:\n", myArray_2D.ndim)
print("Size of an array 2:\n", myArray_2D.size)

Shape of array 2:
 (2, 4)
Dimensionality of array 2:
 2
Size of an array 2:
 8


<span style="color:black;font-size: 25px; font-family: Arial; font-weight: bold;"> Problem 4:  Create an array with 4 rows and 3 columns of zeros. </span>

In [7]:
import numpy as np

zero = np.zeros((4,3))

print(zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


<span style="color:black;font-size: 25px; font-family: Arial; font-weight: bold;"> Problem 5: Create an array of ones that has 3 rows and 4 columns. </span>

In [9]:
import numpy as np

one = np.ones((3,4))

print(one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


<span style="color:black;font-size: 25px; font-family: Arial; font-weight: bold;"> Problem 6: Create an array containing integers 4 to 13 inclusive.</span>

In [11]:
import numpy as np

range1 = np.arange(4,14)

print(range1)

[ 4  5  6  7  8  9 10 11 12 13]


<span style="color:black;font-size: 25px; font-family: Arial; font-weight: bold;"> Problem 7: Create a 2 by 2 array containing '4' in each position.</span>

In [12]:
import numpy as np

print(np.full((2,2),4))

[[4 4]
 [4 4]]


<span style="color:black;font-size: 25px; font-family: Arial; font-weight: bold;"> Problem 8: Create a 3 by 3 array with random floats in [0, 10].</span>

In [13]:
import numpy as np

print(np.random.random((3,3))*10)

[[1.46785284 8.57459571 4.57627205]
 [8.82642524 2.725168   3.55103038]
 [9.18771549 7.07305014 1.73936416]]


<span style="color:black;font-size: 25px; font-family: Arial; font-weight: bold;"> Problem 9: Use this array for the following practice:<br></span>
<span style="color:black;font-size: 25px; font-family: Arial; font-weight: bold;">myArray = np.array([[11,12,13], [14,15,16], [17,18,19]])<br></span>
<span style="color:black;font-size: 25px; font-family: Arial; font-weight: bold;">a) Get a subarray of the first row and first 2 columns.<br></span>
<span style="color:black;font-size: 25px; font-family: Arial; font-weight: bold;">b) change all elements in 1st and second row to 0.</span>

In [24]:
## a) Get a subarray of the first row and first 2 columns.
import numpy as np

myArray = np.array([[11,12,13], [14,15,16], [17,18,19]])

myArray_new = myArray[0,:2]

print(myArray_new)

[11 12]


In [25]:
##b) change all elements in 1st and second row to 0
myArray[:2,:] = 0

print(myArray)

[[ 0  0  0]
 [ 0  0  0]
 [17 18 19]]


<span style="color:black;font-size: 25px; font-family: Arial; font-weight: bold;"> Problem 10: Create an array that contains [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20] and reverse the order.</span>

In [18]:

myArray = np.arange(21)
print(myArray)
print(myArray[::-1])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


<span style="color:black;font-size: 25px; font-family: Arial; font-weight: bold;"> Problem 11: Find the elements that are the same in both arrays.<br /></span>
<span style="color:black;font-size: 25px; font-family: Arial; font-weight: bold;"> myArray_1 = np.array([2,2,3,4]).<br /></span>
<span style="color:black;font-size: 25px; font-family: Arial; font-weight: bold;"> myArray_2 = np.array([3,2,3,4]).</span>

In [20]:
import numpy as np

myArray_1 = np.array([2,2,3,4])
myArray_2 = np.array([3,2,3,4])

print("First array:", myArray_1)
print("Second array:", myArray_2, "\n")

print(np.where(myArray_1 == myArray_2), "\n")


First array: [2 2 3 4]
Second array: [3 2 3 4] 

(array([1, 2, 3], dtype=int64),) 



<span style="color:black;font-size: 25px; font-family: Arial; font-weight: bold;"> Problem 12: Find elements in myArray_1 that are smaller than or equal to its corresponding element in myArray_2.</span>

In [21]:
import numpy as np

myArray_1 = np.array([2,2,3,4])
myArray_2 = np.array([3,2,3,4])

print("First array:", myArray_1)
print("Second array:", myArray_2, "\n")

print(np.where(myArray_1 <= myArray_2), "\n")

First array: [2 2 3 4]
Second array: [3 2 3 4] 

(array([0, 1, 2, 3], dtype=int64),) 



<span style="color:black;font-size: 25px; font-family: Arial; font-weight: bold;"> Problem 13: Find the elements in myArray_1 that is bigger than 2.</span>

In [22]:
import numpy as np

myArray_1 = np.array([2,2,3,4])

print("First array:", myArray_1, "\n")

print(myArray_1 > 2)


First array: [2 2 3 4] 

[False False  True  True]


<span style="color:black;font-size: 25px; font-family: Arial; font-weight: bold;"> Problem 14:Convert a 1-D array into a 2-D array with 3 rows.</span>

In [23]:
import numpy as np

exercise_2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])

print("The original array: \n", exercise_2, "\n")

print("Method 1: \n", exercise_2.reshape(3,-1), "\n")

print("Method 2: \n", exercise_2.reshape(3,3))

The original array: 
 [0 1 2 3 4 5 6 7 8] 

Method 1: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 

Method 2: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
